feat: :sparkles: implement setting to store scopes in user settings i…
vivaxy/vscode-conventional-commits pull request #336
Opened 2024-03-27 10:05 UTC by Hobart2967

…nstead of workspace settings

https://github.com/vivaxy/vscode-conventional-commits/issues/335

2024-05-13 08:01 UTC, vivaxy requested changes
Thanks for the PR.
I still have some questions left.

2024-06-08 21:55 UTC, Hobart2967 commented on package.nls.json
> +  "extension.configuration.storeScopesGlobally.markdownDescription": "Control whether the extension should store the defined scopes within your workspace settings or your user settings.",
Done :) Please also have a look at the corresponding chinese version. As I do not speak or can write it, I'd appreciate your help :)

2024-06-08 22:03 UTC, Hobart2967 commented on src/lib/prompts/prompt-types.ts
> +  storeGlobal: boolean | undefined;
Good point!

2024-06-08 22:09 UTC, Hobart2967 commented on package.nls.zh-cn.json
> +  "extension.configuration.storeScopesGlobally.markdownDescription": "Control whether the extension should store the defined scopes within your workspace settings or your user settings.",
Done!

2024-06-08 22:09 UTC, Hobart2967 commented on src/lib/prompts/prompt-types.ts
> +  storeGlobal: boolean | undefined;
Done!

2024-06-08 22:09 UTC, Hobart2967 commented on src/lib/commitlint.ts
> +        const error = e as Error;
Done!

2024-06-29 15:11 UTC, vivaxy approved these changes

2024-06-29 15:11 UTC, merged

2024-06-29 15:17 UTC, vivaxy commented
@Hobart2967 Thanks for your PR. I'll try to check and release the extension soon.