feat(prompt)!: :sparkles: add prepend breaking change
vivaxy/vscode-conventional-commits pull request #96
Opened 2021-03-21 12:59 UTC by yi-Xu-0100

Add a prompt for the breaking news.

BREAKING CHANGE: Add a new prompt for the breaking change before the footer.

Close #39

2021-03-21 13:10 UTC, yi-Xu-0100 commented
@vivaxy It will make a breaking change, because it adds a prompt before the footer and if the changes does not know for the user, they may write a footer as the breaking change. It will skip check if they were setting the auto commit option. 😥

Or we can add a window to make a prompt for the breaking change which can be setting never showing next time. 🎈

Or we can add a option about enable the breaking change prompt. ✨

2021-03-23 14:38 UTC, vivaxy requested changes
Thx!

2021-03-23 14:38 UTC, vivaxy commented on src/lib/commit-message.ts
> +    message = message.replace(': ', '!: ');
We can have the `!:` implemented in the `serializeHeader` function, other than `serializeHeader` first and `replace` after.

2021-03-23 14:38 UTC, vivaxy commented on src/lib/prompts.ts
> +          question.name === 'footer' ||
Is this name `breakingChange`?

2021-03-23 23:57 UTC, yi-Xu-0100 commented
Here will redesign after the #99, or they will redesign with together.

The latest change is rebased with the master branch, which may have no change than before. 😅

I will make a request about review if all things are done, please give me more time. 😋

2021-03-24 08:55 UTC, closed without merging